export enum ViewKey {
  SUB_SECRETARIAS = 'sub-secretarias',
  DIRECCIONES = 'direcciones',
  DEPARTAMENTOS = 'departamentos',
  PAIS='pais',
  PROVINCIA='provincia',
  LOCALIDAD='localidad',
  ESTADO_OBRA='estado-obra',
  FIANCIAMIENTO='financiamiento',
  MODIFICACION_OBRA='modificacion-obra',
  PARALIZACION_OBRA='paralizacion-obra',
  PROGRAMA_OBRA='programa-obra',
  REPRESENTANTE_EMPRESA='representante-empresa',
  TRAMITE='tramite',
  INSPECTOR='inspector',
}
